### ISSUE TITLE
Stepper drive fans don't work

### ISSUE THREAD

**Issue by eduwes** [tenlog/TL-D3V2#1]
After upgrading to 2.0.8.030 the stepper driver fans on the underside of the TL-D3 v2 no longer work. On the factory delivered version, they were working.

Thanks,

**Comment by tenlog** [comment]
Ok, if you have other questions later, please send related videos to ***@***.***, thank you.
Sarah






发件人：eduwes ***@***.***>
发送日期：2022-11-16 11:04:10
收件人：tenlog/TL-D3V2 ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[tenlog/TL-D3V2] Stepper drive fans don't work (Issue #1)

After upgrading to 2.0.8.030 the stepper driver fans on the underside of the TL-D3 v2 no longer work. On the factory delivered version, they were working.
Thanks,

**Comment by tenlog** [comment]
We have fixed this issue in version V2.0.8.031， Thank you!
